export const CREATE_MOVIE = "CREATE_MOVIE";
export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS";
export const CREATE_MOVIE_FAIL = "CREATE_MOVIE_FAIL";

export const DESTROY_MOVIE = "DESTROY_MOVIE";
export const DESTROY_MOVIE_SUCCESS = "DESTROY_MOVIE_SUCCESS";
export const DESTROY_MOVIE_FAIL = "DESTROY_MOVIE_FAIL";
