export const FETCH_MOVIELISTS = "FETCH_MOVIELISTS";
export const FETCH_MOVIELISTS_SUCCESS = "FETCH_MOVIELISTS_SUCCESS";
export const FETCH_MOVIELISTS_FAIL = "FETCH_MOVIELISTS_FAIL";

export const CREATE_MOVIELIST = "CREATE_MOVIELIST";
export const CREATE_MOVIELIST_SUCCESS = "CREATE_MOVIELIST_SUCCESS";
export const CREATE_MOVIELIST_FAIL = "CREATE_MOVIELIST_FAIL";

export const DESTROY_MOVIELIST = "DESTROY_MOVIELIST";
export const DESTROY_MOVIELIST_SUCCESS = "DESTROY_MOVIELIST_SUCCESS";
export const DESTROY_MOVIELIST_FAIL = "DESTROY_MOVIELIST_FAIL";
